import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import styles from "../styles/Search.module.css";
import Search from "./search";
export default function Home() {
  return (
    <div className={`background ${styles.container}`}>
      <Head>
        <title>Create Next App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&family=Unica+One&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search></Search>
    </div>
  );
}
