import React, {useState ,useEffect} from 'react'
import Head from "next/head";
import Image from 'next/image'
import Link from 'next/link'
import SearchSelect from '../components/SearchSelect';
import styles from "../styles/Search.module.css"
import useApi from '../services/useApi';
import useUtils from '../services/useUtils';
import  Router from 'next/router';

function Search() {
  const [getSearchingUsers] = useApi(); 
  const [platform,setPlatform] = useState("uno");
  const [usersList, setUsersList] = useState() // aqui se almacena la lista de usuarios que devuelve la api.
  const [userInput, setUserInput] = useState('') // el id de usuario que a introducido el usuario.
  const [parseUser] = useUtils();
  const [loading,setLoading] = useState();

  const start = () =>{
    setLoading(true)
  }
  const end = () =>{
    setLoading(false)
  }
  
  useEffect(() =>{
    
    getSearchingUsers(userInput,platform,setUsersList)
  },[userInput,platform]);

  useEffect(() =>{
    Router.events.on("routeChangeStart", start);
    Router.events.on("routeChangeComplete", end);
    Router.events.on("routeChangeError", start);
  },[])


  return (
    
    <div className={`background ${styles.searchContainer}`}>
      
      {loading?
      (<div className={`jus-center al-center ${styles.loading}`}>
          <h3>Loading...</h3>
      </div>):(
        <>
        <Head>
        <title>Gamics - Search</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin="true"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" crossOrigin="true"/>
      </Head>

      <div className={`mb-32 ${styles.contentContainer}`}>
        <div className='jus-center mb-24'>
        
          <Image width={100} height={100} crossOrigin="anonymous" src="/img/LogoCircleDark.png" alt='imagen logo'></Image>
        </div>
        <div className={styles.formContainer}>
          <h5 className='text-center  mb-32'>
          SEARCH YOUR WARZONE PROFILE
          </h5>
          <SearchSelect platform={platform} setPlatform={setPlatform}></SearchSelect>
          <input type='text' className={`m-12  ${styles.searchInput}`} value={userInput.value} onChange={(value) => setUserInput(value.target.value)} placeholder='INSERT ID'></input>
          {usersList ?
          <div className={` mb-24 pt-8 pb-8 ${styles.userList}`}>
            {usersList.data.map((item, index) => {
                return (
                  <div className='p-12' key={item.accountId}>
                    <Link href={`/profile/${platform}/${parseUser(item.username)}`} crossOrigin="anonymous" key={item.accountId}><a className={`mb-24 ${styles.result} text-center`}>{item.username}</a></Link>
                  </div>  
                  )
              })}
          </div> 
            :null
                        }
          <Link href={`/profile/${platform}/${parseUser(userInput)}`} crossOrigin="anonymous"><a className={`button  mb-24 ${styles.searchBtn} text-center`}>SEARCH</a></Link>
          <h6 className='text-center text-mute'>
            SEARCH YOUR PROFILE OR THE PROFILE OF YOUR FRIENDS
          </h6>
        </div>
      </div>
      </>
      )
      }
      
    </div>
  )
}

export default Search
